# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipedream < Formula
  desc "PipeDream - Maintainable script automation"
  homepage "https://layer9.berlin/"
  version "0.31.0"
  license "GPL-3.0-or-later"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Layer9Berlin/PipeDream/releases/download/v0.31.0/brew_pipedream_0.31.0_darwin_amd64.tar.gz"
    sha256 "86708b325bb90a828f74a44a9cac13639e69f8d160870a77e0eb6d32dff14674"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/Layer9Berlin/PipeDream/releases/download/v0.31.0/brew_pipedream_0.31.0_linux_amd64.tar.gz"
    sha256 "b043c6b5fd9854bf3ec82f1c90cc63ea58d24fedcd89e136a775957047a93e89"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/Layer9Berlin/PipeDream/releases/download/v0.31.0/brew_pipedream_0.31.0_linux_arm64.tar.gz"
    sha256 "d4d490c34cae49f2561d3c5576fec15814041b3375d76bbff6e2ce329487c57c"
  end

  def install
    bin.install "pipedream"
    include.install Dir["include/*"]
    ln_s("#{include}/pipedream_pipes", "#{bin}", force: true)
    system "#{bin}/pipedream"
    ln_s("#{bin}/pipedream", "#{bin}/p", force: true)
  end

  test do
    system "#{bin}/pipedream --version"
  end
end
