# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipedream < Formula
  desc "PipeDream - Maintainable script automation"
  homepage "https://layer9.berlin/"
  version "0.12.0"
  license "GPL-3.0-or-later"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Layer9Berlin/PipeDream/releases/download/v0.12.0/pipedream_0.12.0_darwin_amd64.tar.gz"
    sha256 "751591c1cae916de78dbcdf938514db51df98258dbaf8fabe078a02030c68ca2"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/Layer9Berlin/PipeDream/releases/download/v0.12.0/pipedream_0.12.0_linux_amd64.tar.gz"
    sha256 "57b1a7db75cfadb74c672f4d29cb6e1c6fc29eac7a83e3f637cf4c70394093aa"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/Layer9Berlin/PipeDream/releases/download/v0.12.0/pipedream_0.12.0_linux_arm64.tar.gz"
    sha256 "6ba1683fb3b4818ea2550486ff7c4c403b6060cbc7ca2e14064730c26f3a7a88"
  end

  def install
    bin.install "pipedream"
    include.install Dir["include/*"]
    bin.install_symlink #{include}/pipedream_pipes
    system "#{bin}/pipedream"
  end

  test do
    system "#{bin}/pipedream --version"
  end
end
